### PR TITLE
Fetch the openapi.json file and keep it versioned

### PR DESCRIPTION
**Pull request by multani**
I reformated the file with `jq`: it's the same version as before, just with all the fields correctly sorted.

### CODE REVIEW

**Comment by multani** [comment]
@Sijoma :wave:

**Review by Sijoma — APPROVED** [review]
Thanks! Lgtm. 
We probably also need to update I guess there are some new APIs

**Comment by multani** [comment]
The update is in #4 ;)

**Comment by multani** [comment]
I can't merge, can you do it when you have time?

I'll "open" #4 afterwards.

**Pull request merged**
